# docker-compose.yml
version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000" # Expose gateway to your host machine on port 8000
    environment:
      - DB_SERVICE_URL=http://db-service:8002
      - MRI_SERVICE_URL=http://model-mri:7860
      - TABULAR_SERVICE_URL=http://model-tabular:8002
      - PDF_SERVICE_URL=http://pdf-reports:8003
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - db-service
      - model-mri
      - model-tabular
      - pdf-reports

  db-service:
    build: ./services/db
    ports:
      - "8001:8002" # Map container port 8002 to host port 8001 (optional)
    environment:
      - DATABASE_URL=${DATABASE_URL}

  model-mri:
    build: ./services/model_mri
    ports:
      - "7860:7860"

  model-tabular:
    build: ./services/model_tabular
    ports:
      - "8002:8002"

  pdf-reports:
    build: ./services/pdf_reports
    ports:
      - "8003:8003"
